import { CheckIcon, CopyIcon } from 'lucide-react'
import { type ComponentProps, useEffect, useState } from 'react'
import { codeToHtml } from 'shiki'
import { twMerge } from 'tailwind-merge'
import { IconButton } from './icon-button'

interface CodeBlockProps extends ComponentProps<'div'> {
  code: string
  language?: string
}

export function CodeBlock({
  className,
  code,
  language = 'json',
  ...props
}: CodeBlockProps) {
  const [parsedCode, setParsedCode] = useState('')
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    if (code) {
      codeToHtml(code, { lang: language, theme: 'vesper' }).then((parsed) =>
        setParsedCode(parsed),
      )
    }
  }, [code, language])

  async function handleCopy() {
    await navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div
      className={twMerge(
        'relative rounded-lg border border-zinc-700 overflow-x-auto',
        className,
      )}
      {...props}
    >
      <div className="absolute top-2 right-2 z-10">
        <IconButton
          icon={
            copied ? (
              <CheckIcon className="size-4 text-emerald-400" />
            ) : (
              <CopyIcon className="size-4" />
            )
          }
          onClick={handleCopy}
          className="cursor-pointer"
        />
      </div>

      <div
        className="[&_pre]:p-4 [&_pre]:text-sm [&_pre]:font-mono [&_pre]:leading-relaxed [&_pre]:!bg-transparent"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: safe because it's generated by shiki
        dangerouslySetInnerHTML={{ __html: parsedCode }}
      />
    </div>
  )
}
